# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0

  pre_build:
    commands:
      - echo Restore started on `date`
      - echo "CURRENT DIR `pwd`"
      - dotnet restore WebApi/WebApi/WebApi.csproj

  build:
    commands:
      - echo Build started on `date`
      - dotnet build WebApi/WebApi/WebApi.csproj

  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -o ./build-output WebApi/WebApi/WebApi.csproj

artifacts:
  name: DEMO_API_Build_#$CODEBUILD_BUILD_NUMBER
  base-directory: './build-output'
  files:
    - ./**/*